### ISSUE TITLE
As a React Reconciler?

### ISSUE THREAD

**Issue by dakom** [WebReflection/neverland#12]
Don't shoot me!

Just want to put this out there as an idea to _explore_... maybe...

What if instead of building Neverland on dom-augmentor, it was rather built as a react reconciler? i.e. not to replace React, but rather to replace ReactDOM.

I'd assume even exploring this at all would mean no more JSX, which is okay imho.

I'm not sure if this makes sense, but I think it's a worthwhile idea to at least think about before dismissing it out of hand.

Having React manage the hooks magic, but lighterhtml handling the actual dom updates and diffing, sounds like a cool idea at a glance.

**Comment by WebReflection** [comment]
AFAIK React is strongly coupled with its vDOM, while my idea is that you don't need that overhead, so I create alternatives.

I've been updating too enthusiastically these days and I did a mess, in terms of stability, but since augmentor is new, and the dom-augmentor doesn't really change it a single bit, it just adds already battle tested disconnected lib from hyperHTML, I prefer to fix it, or make it as-good-as, 'cause there are already third parts using it, and I want to use it myself.

The boilerplate that brings React on the plate is, IMO, kinda unbearable.

lighterhtml with dom-augmentor already works out of the box and reliably, it's just neverland that needs too much magic with these components, but I'll eventually, hopefully, fix that too.

That being said, I'd be happy if anyone else would take lighterhtml and use it within React, I just don't see myself creating such hybrid.

Closing, as there's no intention to throw way neverland ... it needs basically only one fix at this point (the rest is eventually augmentor gotchas) and I'd like to find that fix.
