### ISSUE TITLE
Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by CaptainJKoB** [WebReflection/neverland#46]
Hello 👋

After some testing I came across this error in the example bellow.
> Cannot read property 'fn' of undefined
```javascript
import { neverland as $, html, render, useState } from 'https://unpkg.com/neverland?module';

const Button = (props) => {
  const [count, setCount] = useState(0);
  const onClick = () => setCount(count + 1);
  return html`<button onClick="${ onClick }">${ props.title } ${ count }</button>`
};

const App = $((props) => {
  return html`<div>${ Button(props) }</div>`;
});

const appProps = {
  title: 'Click:'
};

render(document.body, html`<div class="container">${ App(appProps) }</div>`);
```

It starts working if I change the the hole in the template to an Array in `render`.
```javascript
render(document.body, html`<div class="container">${[ App(appProps) ]}</div>`);
```

And this brought me to a question.
Do you need to wrap every component into `neverland` or is the main `App` component enough?
Because in the example above the Hooks work inside the `Button` component, whilst the only component wrapped into `neverland` is `App`, and I am not sure if this isn't an anti-pattern.

Thanks again for the great work. :)

**Comment by WebReflection** [comment]
You need to wrap **only** if the following criteria is satisfied:
  * the component returns `html` or `svg`
  * **and**
  * the component uses _any_ kind of hook

Accordingly, your example should wrap `Button`, but not `App`, as it's the button that uses the state, the `App` is just a container with no hooks whatsoever.

Here [the codepen that works](https://codepen.io/WebReflection/pen/oNNrBJX?editors=0010) via this content:

```js
import { neverland as $, html, render, useState } from 'https://unpkg.com/neverland?module';

// button returns a component and it uses hoks: wrap it!
const Button = $((props) => {
  const [count, setCount] = useState(0);
  const onClick = () => setCount(count + 1);
  return html`<button onclick="${onClick}">${props.title} ${count}</button>`
});

// just a container, no need to wrap it
const App = (props) => html`<div>${[Button(props)]}</div>`;

const appProps = {title: 'Click:'};

render(document.body, html`<div class="container">${App(appProps)}</div>`);
```

The fact `Button` needs to be in an Array in order to work is a bug, thanks for filing it.

**Comment by WebReflection** [comment]
To better understand how the wrap works, when you wrap a container, but none of its children, the state will be shared with all of them. You pretty much never want that to happen though, so if a component uses hooks related to its state (event external composed hooks) you need to wrap it, otherwise it cannot possibly ever work in isolation, and you'll have side effects in the outer wrapped function.

More regarding how hooks work here: https://medium.com/@WebReflection/demystifying-hooks-f55ad885609f

**Comment by CaptainJKoB** [comment]
Thank you for the clarification and help. I am gonna give it a read :+1:

**Comment by WebReflection** [comment]
This has been fixed, but also a note in the REDME has been added https://github.com/WebReflection/neverland/#when-should-i-wrap-components-as-in-const-comp----html
