### ISSUE TITLE
Efficient rendering of array-mapped components

### ISSUE THREAD

**Issue by luke-thorburn** [WebReflection/neverland#63]
Not an issue, but a question about best practice.

Often there is a need for components with a variable number of subcomponents, such as a `List` component with a variable number of `Item`s. Currently, I am implementing such components by storing the identifying details of the list items as an array in the `List` state, and generating the items using `.map()`, like so:

```js
const {neverland: $, render, html, useState} = window.neverland;

const Item = (props) => {
  
  console.log(`Computing stuff for item ${props.id}...`)                       //  <-- Runs every time.
  
  return html`
    <li>
      Item ${props.id}
    </li>`;
}

const List = $(() => {

  const [items, setItems] = useState([
    {id: 2},
    {id: 1},
  ]);
  
  const addItem = () => {
    setItems(prevItems => {
      let items = [...prevItems],
          maxId = Math.max(...prevItems.map(d => d.id));
      items.unshift({
        id: maxId + 1
      })
      return items;
    })
  }
  
  return html`
    <ul>
      ${items.map(item => Item(item))}
    </ul>
    <button onclick="${addItem}">Add item</button>`;

});

render(document.body, html`${List()}`);
```
[CodePen](https://codepen.io/luke-thorburn/pen/VwKKEJJ)

With this implementation, it seems all the items are recomputed or re-rendered from scratch every time the state changes. This is fine in many cases, but sometimes the subcomponents can be quite expensive, and so the unnecessary re-rendering leads to performance issues.

Is there way of implementing this setup more intelligently so that only new/altered subcomponents are re-rendered, wherever they are positioned within the set of subcomponents?

**Comment by WebReflection** [comment]
If you inspect the `<UL>` element you'll see that the only thing that changes *is* the added items and nothing else.
The fact you read the console log does *not* mean the library re-render anything, it means it simply executes the callback, because that's inevitably what happens when you write:

```js
items.map(item => Item(item))
```

Since you update the `List`, and it maps over the list, how would you expect anything to *not* log that?

And bear in mind, this is how hooks work, any framework, any library, it's an inside-out call-stack:
https://webreflection.medium.com/demystifying-hooks-f55ad885609f

If you have very expensive operations, use the `useMemo` utility and guard against unnecessary calls, or initialize states via callbacks, or ... do anything others do in React or Preact as every library works the same and if you invoke a function in a `map` operation, no code can prevent that function from executing each time.

**Comment by WebReflection** [comment]
P.S. in case it wasn't clear: it's fine, your code is fine, it's optimized automatically so nothing renders twice, all nodes render indeed once only without issues, and performance here are blazing fast 👍

**Comment by luke-thorburn** [comment]
@WebReflection Thanks for the help and pointers, web development is not my main area so it is much appreciated. My terminology isn't as precise as it should be.

If I inspect the `<ul>` in the above example, the new list element is being added at the end of the list, but the list item with new content comes first in the list (look at the numbering). This means that all of the existing `<li>`s need to have their content repopulated (because their content changes position), even though this would not be necessary if the new `<li>` was inserted at the start rather than the end. In essence, the same thing occurs if you insert a new item in the middle of the list, or delete one from anywhere except the last position.

![ul](https://user-images.githubusercontent.com/5829453/101740142-93385e00-3b1c-11eb-9e7b-05b8b711b1f1.gif)

I get that this is the expected behaviour for my above code, and how most/all frameworks work. But is there a way (not using `.map()`) to give the framework the ability to keep track of which element in the JS array corresponds to which DOM element, and hence add or remove only those DOM elements that *have to* change? That is, to only execute the callback on components that are new? I imagine that it may be possible, so long as there is some sort of unique ID on the elements in the JS array.

It's possible I'm missing something fundamental so feel free to bluntly point that out if so.

**Comment by WebReflection** [comment]
OK, this is a different thing ... it's about *keyed* vs *non-keyed* renders, but one thing I'd like to point out is that both *lighterhtml* and *uhtml* are *very fast libraries*, one of the fastest in their category, if not *the* fastest, and updating sparse text nodes, or even attributes, is never a big deal ... that being said:

```js
const Item = (props) => {
  // you can either use the props object
  // in case this is not trashed/re-created per each update
  return html.for(props)`
    <li>
      Item ${props.id}
    </li>`;
}
```

Alternatively you can pass along the container reference and use `html.for(container, props.id)` if props are always new objects, so that somehow the *WeakMap* is freed when their container disappears from the DOM.

Does this solve your issue?

**Comment by luke-thorburn** [comment]
It does, thank you!
